POST http://localhost:8000/signup
content-type: application/json

{
    "username": "isagues2",
    "email": "yebol65547@estudys.com",
    "password": "P4ssword!",
    "name": "isagues"
}
###

POST http://localhost:8000/signup/confirm
content-type: application/json

{
    "username": "isagues2",
    "code": "817917"
}
###

POST http://localhost:8000/signup/resend
content-type: application/json

{
    "username": "isagues2"
}
###

POST http://localhost:8000/login
content-type: application/json

{
    "username": "isagues2",
    "password": "P4ssword!"
}
###

POST http://localhost:8000/refresh
content-type: application/json

{
    "username": "isagues2"
}
